spring:
  profiles:
    active: auth

project-config:
  template-dir: 'D:\Download\spring-demo-master\spring-demo-master\cn\AutoTools\src\main\resources\templates'
  temp-dir: 'C:\Users\wujj\AppData\Local\Temp\AutoTools'
  default-primary-key-name: 'id'
  table-info-dir: 'D:\Download\spring-demo-master\spring-demo-master\cn\AutoTools\src\main\resources\tables'
