management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: dev.DB
    url: jdbc:p6spy:postgresql://192.168.19.12:5432/pdm?stringtype=unspecified

tools-config:
  project-name: pdm
  table-prefix: t_
  default-primary-key: id
  properties:
    pdm-server: 'D:\Project\pdm\pdm-server\src\main\java\com\sdstc\pdm\server'
    service-package: 'com.sdstc.pdm.server.service'
    mapper-package: 'com.sdstc.pdm.server.mapper'
    entity-package: 'com.sdstc.pdm.server.entity'
    request-package: 'com.sdstc.pdm.common.request'
    response-package: 'com.sdstc.pdm.common.response'
    enums-package: 'com.sdstc.pdm.common.enums'
  table-configs:
    - table-name: t_pdm_project_member
      template-to-generate:
        - entity.ftl
        - enum.ftl
        - create_entity_request.ftl
        - entity_ids_request.ftl
        - page_entity_request.ftl
        - update_entity_request.ftl
  template-configs:
    - template-filename: 'service.ftl'
      output-directory: 'service'
      output-filename: '%sTestService.java'
      properties:
        package: 'com.sdstc.pdm.server.service'
#
