management:
  endpoints:
    web:
      exposure:
        include: '*'

    #spring:
    #  datasource:
    ##    driver-class-tableName: org.postgresql.Driver                                                             # 原始的
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver                                                   # 使用p6spy后的
    #    password: HelloWorld
    ##    url: jdbc:postgresql://192.168.13.68:5432/postgres?currentSchema=public&stringtype=unspecified       # 原始的
    #    url: jdbc:p6spy:postgresql://192.168.13.68:5432/postgres?currentSchema=public&stringtype=unspecified  # 使用p6spy后的
    #    username: postgres

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: dev.DB
    url: jdbc:p6spy:postgresql://192.168.19.12:5432/dyf2?currentSchema=dyf&stringtype=unspecified
